### ISSUE TITLE
shareholding pattern data

### ISSUE THREAD

**Issue by shashank-556** [shashank-556/Mfinance#1]
### Add a method in *comp* class to return the latest shareholding pattern of a company
1. DO NOT change or modify other methods
2. *self.sp* is the BeautifulSoup object , use this object to extract the latest shareholding pattern data.
3. Return the final data in the form of a python dictionary or a pandas dataframe.
4. The dictionary returned or the dataframe should have 4 keys (or attributes) - promoter, fii, dii , public.

**Comment by iedr** [comment]
Hi, I will work on this issue!
